<?php

function printPerQ($sqls, $sqlc) {

//$svar1 = "SELECT school_answer_value FROM '$table' WHERE keygen=2";
//$svar2 = "SELECT school_answer_value FROM '$table' WHERE keygen=2";
//$svar3 = "SELECT school_answer_value FROM '$table' WHERE keygen=3";
//$svar4 = "SELECT school_answer_value FROM '$table' WHERE keygen=4";
//$svar5 = "SELECT school_answer_value FROM '$table' WHERE keygen=5";
//$cvar1 = (int)$table[0]->company_answer_value;
//$cvar2 = "SELECT company_answer_value FROM '$table' WHERE keygen=2";
//$cvar3 = "SELECT company_answer_value FROM '$table' WHERE keygen=3";
//$cvar4 = "SELECT company_answer_value FROM '$table' WHERE keygen=4";
//$cvar5 = "SELECT company_answer_value FROM '$table' WHERE keygen=5";
$counter = 0;


	echo '<div style="width: 600px; height: 800px;" id="graph"></div>
<script>
    Plotly.plot("graph", [{
	displayModeBar: false,	
  type: "bar",
  name: "haluttu",
  x:	[' . json_encode((int)$sqlc[0]->answer_max - $sqlc[0]->answer_min) . ', 
		' . json_encode((int)$sqlc[1]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[2]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[3]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[4]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[5]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[6]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[7]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[8]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[9]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[10]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[11]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[12]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[13]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[14]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[15]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[16]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[17]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[18]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[19]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[20]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[21]->answer_max - $sqlc[1]->answer_min) . ',
		' . json_encode((int)$sqlc[22]->answer_max - $sqlc[1]->answer_min) . '],
  base:	[' . json_encode((int)$sqlc[0]->answer_min) . '-0.05, 
		' . json_encode((int)$sqlc[1]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[2]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[3]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[4]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[5]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[6]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[7]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[8]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[9]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[10]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[11]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[12]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[13]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[14]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[15]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[16]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[17]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[18]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[19]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[20]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[21]->answer_min) . '-0.05,
		' . json_encode((int)$sqlc[22]->answer_min) . '-0.05],
  y:	["setti1",
		"setti2",
		"setti3",
		"setti4",
		"setti5",
		"setti6",
		"setti7",
		"setti8",
		"setti9",
		"setti10",
		"setti11",
		"setti12",
		"setti13",
		"setti14",
		"setti15",
		"setti16",
		"setti17",
		"setti18",
		"setti19",
		"setti20",
		"setti21",
		"setti22",
		"setti23",],
  marker: {
    color: ["rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)",
			"rgba(255, 99, 132, 0.2)"]
  },
  orientation: "h",
  offset: 0
},{
	displayModeBar: false,
  type: "bar",
  x: 	[0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05,
		0.05],
  name: "vastattu",
  base: [' . json_encode((int)$sqls[0]->answer_val) . ',
		' . json_encode((int)$sqls[1]->answer_val) . ',
		' . json_encode((int)$sqls[2]->answer_val) . ',
		' . json_encode((int)$sqls[3]->answer_val) . ',
		' . json_encode((int)$sqls[4]->answer_val) . ',
		' . json_encode((int)$sqls[5]->answer_val) . ',
		' . json_encode((int)$sqls[6]->answer_val) . ',
		' . json_encode((int)$sqls[7]->answer_val) . ',
		' . json_encode((int)$sqls[8]->answer_val) . ',
		' . json_encode((int)$sqls[9]->answer_val) . ',
		' . json_encode((int)$sqls[10]->answer_val) . ',
		' . json_encode((int)$sqls[11]->answer_val) . ',
		' . json_encode((int)$sqls[12]->answer_val) . ',
		' . json_encode((int)$sqls[13]->answer_val) . ',
		' . json_encode((int)$sqls[14]->answer_val) . ',
		' . json_encode((int)$sqls[15]->answer_val) . ',
		' . json_encode((int)$sqls[16]->answer_val) . ',
		' . json_encode((int)$sqls[17]->answer_val) . ',
		' . json_encode((int)$sqls[18]->answer_val) . ',
		' . json_encode((int)$sqls[19]->answer_val) . ',
		' . json_encode((int)$sqls[20]->answer_val) . ',
		' . json_encode((int)$sqls[21]->answer_val) . ',
		' . json_encode((int)$sqls[22]->answer_val) . '],
  y: 	["setti1",
		"setti2",
		"setti3",
		"setti4",
		"setti5",
		"setti6",
		"setti7",
		"setti8",
		"setti9",
		"setti10",
		"setti11",
		"setti12",
		"setti13",
		"setti14",
		"setti15",
		"setti16",
		"setti17",
		"setti18",
		"setti19",
		"setti20",
		"setti21",
		"setti22",
		"setti23",],
  marker: {
    color: ["orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange",
			"orange"]
  },
  orientation: "h",
  offset: 0
}], {
	displayModeBar: false,
  yaxis: {
    autorange: "reversed"
  }
}, {displayModeBar: false})                             
</script>';
	$counter = $counter + 1;
}


?>
